# Generated by Django 3.2.13 on 2022-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SheikhUmaid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Client',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='Role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='TechUsed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='Year',
            field=models.IntegerField(default=20),
        ),
    ]
