# Generated by Django 3.2.13 on 2022-06-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SheikhUmaid', '0002_auto_20220611_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ContentType',
            field=models.CharField(default='Static', max_length=30),
        ),
    ]
